USE [master]
GO

/****** Object:  Database [SeniorDb]    Script Date: 4.02.2023 20:42:01 ******/
CREATE DATABASE [SeniorDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SeniorDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SeniorDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SeniorDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SeniorDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SeniorDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SeniorDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SeniorDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SeniorDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SeniorDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SeniorDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [SeniorDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SeniorDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SeniorDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SeniorDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SeniorDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SeniorDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SeniorDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SeniorDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SeniorDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SeniorDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SeniorDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SeniorDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SeniorDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SeniorDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SeniorDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SeniorDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SeniorDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SeniorDb] SET RECOVERY FULL 
GO

ALTER DATABASE [SeniorDb] SET  MULTI_USER 
GO

ALTER DATABASE [SeniorDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SeniorDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SeniorDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SeniorDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SeniorDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SeniorDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SeniorDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SeniorDb] SET  READ_WRITE 
GO

